import pytest

from chemutils.protein.pdb.link import LINKLine, parse_link_line


@pytest.mark.parametrize(
    ["line", "expected"],
    [
        (
            "LINK         O   GLY A  49                NA    NA A6001     1555   1555  2.98  ",
            LINKLine(
                atom_name1="O",
                alt_loc1=None,
                res_name1="GLY",
                chain_id1="A",
                seq_num1=49,
                insertion_code1=None,
                atom_name2="NA",
                alt_loc2=None,
                res_name2="NA",
                chain_id2="A",
                seq_num2=6001,
                insertion_code2=None,
                sym1="1555",
                sym2="1555",
                length=2.98,
            ),
        ),
        (
            "LINK         OG1 THR A  51                NA    NA A6001     1555   1555  2.72  ",
            LINKLine(
                atom_name1="OG1",
                alt_loc1=None,
                res_name1="THR",
                chain_id1="A",
                seq_num1=51,
                insertion_code1=None,
                atom_name2="NA",
                alt_loc2=None,
                res_name2="NA",
                chain_id2="A",
                seq_num2=6001,
                insertion_code2=None,
                sym1="1555",
                sym2="1555",
                length=2.72,
            ),
        ),
        (
            "LINK         OD2 ASP A  66                NA    NA A6001     1555   1555  2.72  ",
            LINKLine(
                atom_name1="OD2",
                alt_loc1=None,
                res_name1="ASP",
                chain_id1="A",
                seq_num1=66,
                insertion_code1=None,
                atom_name2="NA",
                alt_loc2=None,
                res_name2="NA",
                chain_id2="A",
                seq_num2=6001,
                insertion_code2=None,
                sym1="1555",
                sym2="1555",
                length=2.72,
            ),
        ),
        (
            "LINK         NE  ARG A  68                NA    NA A6001     1555   1555  2.93  ",
            LINKLine(
                atom_name1="NE",
                alt_loc1=None,
                res_name1="ARG",
                chain_id1="A",
                seq_num1=68,
                insertion_code1=None,
                atom_name2="NA",
                alt_loc2=None,
                res_name2="NA",
                chain_id2="A",
                seq_num2=6001,
                insertion_code2=None,
                sym1="1555",
                sym2="1555",
                length=2.93,
            ),
        ),
        (
            "LINK         C21 2EG A   7                 C22 2EG B  19     1555   1555  1.56  ",
            LINKLine(
                atom_name1="C21",
                alt_loc1=None,
                res_name1="2EG",
                chain_id1="A",
                seq_num1=7,
                insertion_code1=None,
                atom_name2="C22",
                alt_loc2=None,
                res_name2="2EG",
                chain_id2="B",
                seq_num2=19,
                insertion_code2=None,
                sym1="1555",
                sym2="1555",
                length=1.56,
            ),
        ),
        (
            "LINK         SG BCYS A 727                 C14BLIG A1026     1555   1555        ",
            LINKLine(
                atom_name1="SG",
                alt_loc1="B",
                res_name1="CYS",
                chain_id1="A",
                seq_num1=727,
                insertion_code1=None,
                atom_name2="C14",
                alt_loc2="B",
                res_name2="LIG",
                chain_id2="A",
                seq_num2=1026,
                insertion_code2=None,
                sym1="1555",
                sym2="1555",
                length=None,
            ),
        ),
        (
            "LINK        AB12KGLY A1234X               CD34JALA B5678Y  123456 654321 42.12  ",
            LINKLine(
                atom_name1="AB12",
                alt_loc1="K",
                res_name1="GLY",
                chain_id1="A",
                seq_num1=1234,
                insertion_code1="X",
                atom_name2="CD34",
                alt_loc2="J",
                res_name2="ALA",
                chain_id2="B",
                seq_num2=5678,
                insertion_code2="Y",
                sym1="123456",
                sym2="654321",
                length=42.12,
            ),
        ),
    ],
)
def test_parse_link_line(line, expected):
    assert parse_link_line(line) == expected
