# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow cannot be called, as it calls out to other workflows.
# You can use it as a model for your own repo.

name: Run full workflow

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request: {}
  schedule:
    # Every morning at 5:30am
    - cron: "30 5 * * *"

jobs:
  lint:
    uses: CHARM-Tx/gh-workflows/.github/workflows/pixi-lint.yml@v1
    with:
      environment: '["lint-py310", "lint-py311", "lint-py312"]'
    secrets: inherit

  typing:
    uses: CHARM-Tx/gh-workflows/.github/workflows/pixi-typing.yml@v1
    with:
      environment: '["typing-py310", "typing-py311", "typing-py312"]'
    secrets: inherit

  test:
    uses: CHARM-Tx/gh-workflows/.github/workflows/pixi-test.yml@v1
    with:
      environment: '["test-py310", "test-py311", "test-py312", "test-no-chemaxon"]'
    secrets: inherit

  coverage:
    uses: CHARM-Tx/gh-workflows/.github/workflows/codecov.yml@v1
    needs: [test]
    secrets: inherit

  selection-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sh generate_selection_language.sh
      - run: |
          if [[ $(git diff --exit-code) ]]; then
            echo "::error::Selection language requires regenerating."
            exit 1
          fi

  release:
    uses: CHARM-Tx/gh-workflows/.github/workflows/python-package.yml@v1
    needs: [lint, typing, test]
    secrets: inherit
