from collections.abc import Sequence
from typing import NewType

from ...struc import Molecule

pKaType = NewType("pKaType", int)

class CalculatorPlugin:
    def setMolecule(self, mol: Molecule, /) -> None: ...
    def standardize(self, mol: Molecule, /) -> None: ...
    def run(self) -> bool: ...

class pKaPlugin(CalculatorPlugin):
    ACIDIC: pKaType
    BASIC: pKaType
    def getpKa(self, index: int, /) -> float: ...
    def setTemperature(self, temperature: float, /) -> None: ...
    def setpH(self, pH: float, /) -> None: ...
    def getMsCount(self) -> int: ...
    def getMsMolecule(self, msIndex: int, /) -> Molecule: ...
    def getSingleMsDistribution(self, msIndex: float) -> float: ...
    def setConsiderTautomerization(self, considerTautomerization: bool) -> None: ...
    def isMsCalc(self) -> bool: ...
    def getMacropKaValues(self, pkatype: pKaType) -> Sequence[float]: ...
    def setMicropKaCalc(self, micro: bool, /) -> None: ...

class MajorMicrospeciesPlugin(CalculatorPlugin):
    def setpH(self, pH: float, /) -> None: ...
    def getMajorMicrospecies(self) -> Molecule: ...

class logPPlugin(CalculatorPlugin):
    pass

class logDPlugin(CalculatorPlugin):
    def setpH(self, pH: float, /) -> None: ...
    def setConsiderTautomerization(self, considerTautomerization: bool, /) -> None: ...

class TautomerizationPlugin(CalculatorPlugin):
    def setpH(self, pH: float, /) -> None: ...
    def setTakeCanonicalForm(self, canonical: bool, /) -> None: ...
    def setTakeMajorTautomer(self, major: bool, /) -> None: ...
    def setNormalTautomerGenerationMode(self, normal: bool, /) -> None: ...
    def setDominantTautomerDistributionCalculation(self, distrib: bool, /) -> None: ...
    def getStructure(self, index: int, /) -> Molecule: ...
    def getStructureCount(self) -> int: ...
    def getDominantTautomerDistribution(self, index: int, /) -> float: ...
