import numpy as np
import pytest
from openeye import oechem

from chemutils.molecule import read_molecule_str, write_molecule_str
from chemutils.molecule.construct_molecule import construct_molecule
from chemutils.molecule.equal import assert_mol_equal


@pytest.mark.parametrize(
    ["smiles", "n_heavy_atoms"],
    [
        ("C", 1),
        ("OO", 2),
        ("CC=C", 3),
        ("CC#C", 3),
        ("c1ccccc1", 6),
        ("N[C@@H](C)C(=O)O", 6),
        ("C(H)(H)(H)H", 1),
    ],
)
@pytest.mark.skip("Currently unsupported until 3D embedding can be used for coordinates")
def test_molecule_cyclic(smiles, n_heavy_atoms):
    pos = np.random.randn(n_heavy_atoms, 3).astype(np.float32)

    og_mol = construct_molecule(smiles=smiles, coordinates=pos)

    oechem.OESetSDData(og_mol, "test", "test_data")

    og_sdfstr = write_molecule_str(og_mol, format="SDF")
    re_mol = read_molecule_str(og_sdfstr, format="SDF")
    oechem.OEAssignHybridization(re_mol)
    re_sdfstr = write_molecule_str(re_mol, format="SDF")

    assert og_mol.NumAtoms() == n_heavy_atoms
    assert re_mol.NumAtoms() == n_heavy_atoms

    # first line is empty
    # second line contains a name generated by oechem, not expected to match
    assert og_sdfstr.split("\n")[2:] == re_sdfstr.split("\n")[2:]

    assert_mol_equal(og_mol, re_mol)

    assert oechem.OEGetSDData(og_mol, "test") == "test_data"
    assert oechem.OEGetSDData(re_mol, "test") == "test_data"
