from collections.abc import Sequence

class MolAtom:
    def getAtno(self) -> int: ...
    def getCharge(self) -> int: ...
    def getImplicitHcount(self) -> int: ...
    def getExplicitHcount(self) -> int: ...
    def getValence(self) -> int: ...
    def getParent(self) -> MoleculeGraph: ...

class MolBond:
    def getBondType(self) -> BondType: ...
    def getParent(self) -> MoleculeGraph: ...

class MoleculeGraph:
    def getAtomCount(self) -> int: ...
    def getAtomArray(self) -> Sequence[MolAtom]: ...
    def getBondCount(self) -> int: ...
    def getBondArray(self) -> Sequence[MolBond]: ...
    def getTotalCharge(self) -> int: ...
    def getAtom(self, n: int, /) -> MolAtom: ...
    def getBond(self, n: int, /) -> MolBond: ...
    def indexOf(self, obj: MolAtom | MolBond, /) -> int: ...

class Molecule(MoleculeGraph):
    def dearomatize(self) -> None: ...

class BondType:
    SINGLE: BondType
    DOUBLE: BondType
    TRIPLE: BondType
    AROMATIC: BondType
